Traceback (most recent call last):
  File "D:/nchaurasia/Python-Architect/connect2tech.in-Python/com.c2t.debugging/UsingTraceback.py", line 7, in <module>
    getError()
  File "D:/nchaurasia/Python-Architect/connect2tech.in-Python/com.c2t.debugging/UsingTraceback.py", line 4, in getError
    v = 10/0
ZeroDivisionError: division by zero
